### ISSUE TITLE
Allow content to be defined with datapacks / resources packs

### ISSUE THREAD

**Issue by samuelh2005** [znepb/roadworks#1]
Datapacks and resources packs (refereed to as *packs*) can allow custom content to be added to the game without making a mod. If Roadworks supported *packs* then creators will be able to define custom signs, markings, etc (refereed to as *road objects*) .

This will mean people can create "content packs" which may include *road objects*, etc from other countries (for example "*European-style signage*").

As of 1.21 Minecraft allows custom music and paintings to be made with *packs*, also, other mods like [Patbox's Brewery](https://github.com/Patbox/brewery) or [Minecraft Transit Railway](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway) support custom content with *packs* too.

It would be nice if Roadworks had support for *packs* as it would:
1. increase maintainability of the mod (since you no longer need to manually modify the registry for every *road object*)
2. allow people to create *road objects*

This would require **a big refactor** to achieve however it will greatly improve the options which this mod can have.

**Comment by znepb** [comment]
Added in https://github.com/znepb/roadworks/commit/cd0ad1c07f1526378dceed83882f9fd12213d0db
